version: '3'

services:
  db:
    image: mariadb:latest
    env_file: db.env
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  web:
    build: .
    command:
      ./vendor/wait-for-it/wait-for-it.sh -s db:3306
      --
      python3 manage.py runserver 0.0.0.0:8000
    env_file: web.env
    volumes:
      - ..:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
