# Generated by Django 2.1.5 on 2019-01-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_nullable_category_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'parent')},
        ),
    ]
