# Generated by Django 2.1.5 on 2019-01-21 09:07

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_product_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='products'),
        ),
    ]
